[build]
# WANTED:
# - Testing and assurance that the 3 enabled targets will build on any Desktop system
# - Implementation, testing, and assurance that the 2 Apple targets will build on any Desktop system
#   - Must not depend on platform specific tools (no "if windows do x, if linux do y,...")
target = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-gnu",
  "i686-pc-windows-gnu",
  # "x86_64-apple-darwin",
  # "aarch64-apple-darwin",
]
